

-----------------------------------------------------------------------
--READER TO THE DATABASE MOVIES

USE DATABASE MOVIES;

CREATE ROLE reader;

GRANT USAGE ON DATABASE MOVIES TO ROLE READER;

SHOW SCHEMAS;

GRANT USAGE ON SCHEMA MOVIES.STAGING TO ROLE READER;

GRANT SELECT ON ALL TABLES IN SCHEMA MOVIES.STAGING TO ROLE READER;

GRANT SELECT ON FUTURE TABLES IN SCHEMA MOVIES.STAGING TO ROLE READER;
--GRANT ROLE reader TO USER <your_user_name>;

--READER TO THE DATABASE MOVIES
------------------------------------------------------------------------

--WRITER TO THE DATABASE MOVIES
CREATE ROLE WRITER;
GRANT ROLE READER TO ROLE WRITER;

GRANT USAGE ON DATABASE MOVIES TO ROLE writer;
GRANT USAGE ON SCHEMA MOVIES.STAGING TO ROLE writer;

GRANT INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA MOVIES.STAGING TO ROLE WRITER;
GRANT INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA MOVIES.STAGING TO ROLE WRITER;

--GRANT ROLE writer TO USER <your_user_name>;
------------------------------------------------------------------------
--ANALYST TO THE DATABASE MOVIES
CREATE ROLE ANALYST;
GRANT ROLE WRITER TO ROLE ANALYST;
GRANT USAGE ON DATABASE MOVIES TO ROLE ANALYST;
GRANT USAGE ON SCHEMA MOVIES.STAGING TO ROLE ANALYST;

GRANT CREATE VIEW ON SCHEMA MOVIES.STAGING TO ROLE ANALYST;

GRANT CREATE TABLE ON SCHEMA MOVIES.STAGING TO ROLE ANALYST;

GRANT CREATE TEMPORARY TABLE ON SCHEMA MOVIES.STAGING TO ROLE ANALYST;

GRANT USAGE ON ALL PROCEDURES IN SCHEMA MOVIES.STAGING TO ROLE ANALYST;

GRANT USAGE ON ALL FUNCTIONS IN SCHEMA MOVIES.STAGING TO ROLE ANALYST;

GRANT EXECUTE ON PROCEDURE MOVIES.PUBLIC TO ROLE ANALYST;
GRANT EXECUTE ON FUNCTION MOVIES.STAGING.some_function TO ROLE ANALYST;
GRANT USAGE ON SCHEMA MOVIES.PUBLIC TO ROLE READER;
GRANT SELECT ON ALL TABLES IN SCHEMA MOVIES.PUBLIC TO ROLE READER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA MOVIES.PUBLIC TO ROLE READER;

--GRANT ROLE ANALYST TO USER <YOUR USER>
------------------------------------------------------------------------