SHOW DATABASES;

USE DATABASE GOOGLE_KEYWORDS_SEARCH_DATASET__DISCOVER_ALL_SEARCHES_ON_GOOGLE;

SHOW SCHEMAS;
SHOW TABLES IN SCHEMA DATAFEEDS;

SHOW TABLES IN SCHEMA INFORMATION_SCHEMA;

SHOW * FROM GOOGLE_KEYWORDS;

DESCRIBE TABLE GOOGLE_KEYWORDS_SEARCH_DATASET__DISCOVER_ALL_SEARCHES_ON_GOOGLE;


SHOW TABLES;


USE SCHEMA DATAFEEDS;


SELECT * FROM GOOGLE_KEYWORDS;
