SHOW DATABASES;

USE DATABASE GOOGLE_KEYWORDS_SEARCH_DATASET__DISCOVER_ALL_SEARCHES_ON_GOOGLE;

SHOW SCHEMAS;
SHOW TABLES IN SCHEMA DATAFEEDS;

SHOW TABLES IN SCHEMA INFORMATION_SCHEMA;

SHOW * FROM GOOGLE_KEYWORDS;

DESCRIBE TABLE GOOGLE_KEYWORDS_SEARCH_DATASET__DISCOVER_ALL_SEARCHES_ON_GOOGLE;
DESCRIBE table GOOGLE_KEYWORDS;
USE SCHEMA DATAFEEDS;

SELECT COUNT(*) as Total_Rows
FROM GOOGLE_KEYWORDS;

SELECT MIN(DATE)
FROM GOOGLE_KEYWORDS;

SELECT MAX(DATE)
FROM GOOGLE_KEYWORDS;

SELECT keyword, COUNT(*) AS keyword_count
FROM GOOGLE_KEYWORDS
GROUP BY keyword
ORDER BY keyword_count DESC
LIMIT 10;

SELECT COUNT(DISTINCT KEYWORD) AS UNIQUE_KEYWORD
FROM GOOGLE_KEYWORDS;


SELECT PLATFORM, COUNT(*) AS UNI_PLAT
FROM GOOGLE_KEYWORDS
GROUP BY PLATFORM
ORDER BY UNI_PLAT DESC;

SELECT DISTINCT COUNTRY
FROM GOOGLE_KEYWORDS;



SELECT keyword, COUNT(*) AS keyword_count
FROM GOOGLE_KEYWORDS
WHERE COUNTRY = '752'
GROUP BY COUNTRY, KEYWORD
ORDER BY keyword_count DESC
LIMIT 20;


SELECT COUNTRY, COUNT(*) AS MOST_KEYWORD
FROM GOOGLE_KEYWORDS
WHERE KEYWORD = 'spotify'
GROUP BY COUNTRY
ORDER BY MOST_KEYWORD DESC