[destination.snowflake.credentials]
database = "iFood" # please set me up!
password = "Friskos123!" # please set me up!
username = "Extract_loader" # please set me up!
host = "yk57642.west-europe.azure" # can be found through 
warehouse = "marketing_wh" # please set me up!
role = "ACCOUNTADMIN" # please set me up!